version: '3.6'
services:
  event_service:
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./event_service:/usr/src/app/event_service
      - ./.event-service_data/vscode_server:/root/.vscode-server
    labels:
      caddy.address: api.localhost:80
    environment:
      - HOST=postgres
  event_processor:
    command: sh -c "chmod +x entrypoint.sh && nodemon --exec ./entrypoint.sh"
    environment:
      - DEBUG=${EVENT_PROCESSOR_DEBUG}
      - VERBOSE_OUTPUT=${VERBOSE_OUTPUT}
      - RUN_SCHEDULER=${RUN_SCHEDULER}
      - SCHEDULE_INTERVAL=5
      - SPIDER_NAME=${SPIDER_NAME}
    volumes:
      - ./event_processor:/usr/src/app/event_processor
      - event_processor_data:/usr/src/app/event_processor/data/
      - event_processor_lock:/usr/src/app/event_processor/lock/
      - event_processor_scrapy:/usr/src/app/event_processor/.scrapy/
      - ./.event_processor_data/vscode_server:/root/.vscode-server
  in2it_site:
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./in2it_site:/usr/src/app/in2it_site
      - ./.in2it_site/vscode_server:/root/.vscode-server
    environment:
      - IN2IT_API_URL=${IN2IT_API_URL:-http://api.localhost}
    labels:
      caddy.address: localhost:80
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks: 
      - in2it
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ndscheduler:
    command: "nodemon -u simple_scheduler/scheduler.py"
    volumes:
      - ../ndscheduler:/usr/src/app/ndscheduler
      - ndscheduler_modules:/usr/src/app/ndscheduler/node_modules/
      - ../.ndscheduler_data/vscode_remote:/root/vscode-remote
    environment:
      - DEBUG=${SCHEDULER_DEBUG}
      - HOSTNAME=postgres
volumes:
  ndscheduler_modules:
  postgres_data:
  event_processor_data:
  event_processor_lock:
  event_processor_scrapy: