version: '3.6'
services:
  event_service:
    image: event_service_dev
    ports:
      - "5000:5000"
      - "5858:5858"
    networks: 
      - in2it
    labels:
      caddy.targetport: 5000 
      caddy.rewrite:
      caddy.rewrite.if: "{method} not GET"
      caddy.rewrite.to: /method_not_allowed
      caddy.status: "405 /method_not_allowed"
    environment:
      - URL_SCHEME=${URL_SCHEME:-http}
  event_processor:
    image: event_processor_dev
    ports:
      - "6800:6800"
      - "5860:5860"
    networks: 
      - in2it
  in2it_site:
    image: in2it_site_dev
    ports:
      - "3000:3000"
      - "5859:5859"
    networks: 
      - in2it
    labels:
      caddy.targetport: 3000 
  postgres:
    image: tianon/true
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    command: -log stdout -agree -email in2itchicago@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
    networks: 
      - in2it
  portainer:
    image: "portainer/portainer:1.22.2"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    networks: 
      - in2it
  ndscheduler:
    image: ndscheduler_dev
    ports: 
      - "8888:8888"
      - "5861:5861"
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=simple_scheduler.settings
    networks: 
      - in2it
  pgadmin:
    image: dpage/pgadmin4:4.11
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=7000
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "7000:7000"
    # pgadmin spams logs with http request notifications
    logging:
      driver: none
    networks: 
      - in2it
volumes:
  portainerdata:
  pgadmin_data:
networks:
  in2it:
    external: true