version: '3.6'
services:
  mongo:
  event_service:
    command: ["npm", "run", "debug"]
  event_processor:
    environment:
      - DEBUG=${EVENT_PROCESSOR_DEBUG}
      - VERBOSE_OUTPUT=${VERBOSE_OUTPUT}
      - RUN_SCHEDULER=${RUN_SCHEDULER}
      - SCHEDULE_INTERVAL=1
  in2it_site:
    command: ["npm", "run", "docker-debug"]