version: '3.6'
services:
  event_processor:
    image: "in2itchicago/event_processor"
  event_service:
    image: "in2itchicago/event_service"
    command: ["npm", "run", "start"]
  in2it_site:
    image: "in2itchicago/in2it_site"
    command: ["npm", "run", "start"]