version: '3.6'
services:
  event_processor:
    image: in2itchicago/event_processor:20191013.1
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    environment:
      - DEBUG=0
      - VERBOSE_OUTPUT=0
      - SCHEDULE_INTERVAL=120
      - RUN_SCHEDULER=1
    deploy:
      resources:
        limits:
          # Prevent 100% CPU usage
          cpus: '0.8'
  event_service:
    image: in2itchicago/event_service:20191013.1
    command: "yarn run start:prod"
    labels:
      caddy.address: api.${SERVER_NAME:-localhost}:${SERVER_PORT:-80}
    environment:
      - HOST=/var/run/postgresql
  in2it_site:
    image: in2itchicago/in2it_site:20191013.1
    command: "yarn run start"
    environment:
      - "IN2IT_API_URL=${IN2IT_API_URL_PROD:-http://api.localhost}"
    labels:
      caddy.address: ${SERVER_NAME:-localhost}:${SERVER_PORT:-80} www.${SERVER_NAME:-localhost}:${SERVER_PORT:-80}
  ndscheduler:
    image: in2itchicago/ndscheduler:20191013.1
    command: "python -u simple_scheduler/scheduler.py"
    environment:
      - DEBUG=0
      - HOSTNAME=/var/run/postgresql
  caddy:
    volumes:
      - caddy_certs:/root/.caddy
  pgadmin:
    volumes:
      - /var/run/postgresql:/var/run/postgresql
volumes:
  - caddy_certs: