version: '3.6'
services:
  event_service:
    image: event_service_dev
    ports:
      - "5000:5000"
      - "5858:5858"
    networks: 
      - in2it
    labels:
      caddy.targetport: 5000 
      caddy.rewrite:
      caddy.rewrite.if: "{method} not GET"
      caddy.rewrite.to: /method_not_allowed
      caddy.status: "405 /method_not_allowed"
  event_processor:
    image: event_processor_dev
    ports:
      - "6800:6800"
      - "5860:5860"
    networks: 
      - in2it
  splash:
    image: "scrapinghub/splash:3.4.1"
    ports:
      - "8050:8050"
    networks: 
      - in2it
    command: --disable-browser-caches --dont-log-args=lua_source
  in2it_site:
    image: in2it_site_dev
    ports:
      - "3000:3000"
      - "5859:5859"
    networks: 
      - in2it
    labels:
      caddy.targetport: 3000 
  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.6-alpine
    command: -log stdout -agree -email in2itchicago@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global
    networks: 
      - in2it
  ndscheduler:
    image: ndscheduler_dev
    ports: 
      - "8888:8888"
      - "5861:5861"
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=simple_scheduler.settings
    networks: 
      - in2it
  # these services are only used in dev
  pgadmin:
    image: tianon/true
  postgres:
    image: tianon/true
  portainer:
    image: tianon/true
networks:
  in2it:
    external: true