version: '3'
services:
  event_processor:
    image: "in2itchicago/event_processor:20190311.1"
    command: ["python", "-u", "runner.py"]
    environment:
      - DEBUG=0
      - VERBOSE_OUTPUT=0
      - SCHEDULE_INTERVAL=120
  event_service:
    image: "in2itchicago/event_service:20190311.1"
    command: ["npm", "run", "start"]
  in2it_site:
    image: "in2itchicago/in2it_site:20190311.1"
    command: ["npm", "run", "start"]
  nginx:
    image: "nginx:1.15.8"