version: '3.6'
services:
  data_engine:
    image: "in2itchicago/data_engine"
  clipboard_db_client:
    image: "in2itchicago/clipboard_db_client"
    command: ["npm", "run", "start"]
  clipboard_site:
    image: "in2itchicago/clipboard_site"
    command: ["npm", "run", "start"]