version: '3.2'
services:
  event_service:
    command: ["npm", "run", "dev"]
    volumes:
      - ./event_service:/usr/src/app/event_service
      # hack to prevent mounting node_modules
      - /usr/src/app/event_service/node_modules/
  event_processor:
    # -L runs nodemon in legacy mode (necessary over Docker)
    command: bash -c "chmod +x entrypoint.sh && ./node_modules/nodemon/bin/nodemon.js -L --exec ./entrypoint.sh"
    environment:
      - DEBUG=${EVENT_PROCESSOR_DEBUG}
      - VERBOSE_OUTPUT=${VERBOSE_OUTPUT}
      - SCHEDULE_INTERVAL=5
    volumes:
      - ./event_processor:/usr/src/app/event_processor
      - /usr/src/app/event_processor/node_modules/
      - event_processor_data:/usr/src/app/event_processor/data/
      - event_processor_lock:/usr/src/app/event_processor/lock/
      - event_processor_scrapy:/usr/src/app/event_processor/.scrapy/
  in2it_site:
    command: ["npm", "run", "docker-debug"]
    volumes:
      - ./in2it_site:/usr/src/app/in2it_site
      - /usr/src/app/in2it_site/node_modules/
  nginx:
    command: bash -c "chmod +x entrypoint.sh && nodemon -L --exec ./entrypoint.sh"
    environment:
      - SERVER_NAME=localhost
volumes:
  event_processor_data:
  event_processor_lock:
  event_processor_scrapy: