version: '3.6'
services:
  clipboard_db:
    image: "mongo:4.1.6"
    volumes:
      - mongodata:/data/db
  clipboard_db_client:
    image: "clipboard_db_client"
  data_engine:
    image: "data_engine"
  clipboard_site:
    image: "clipboard_site"
  nginx:
    image: "nginx:1.15.8"
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "0.0.0.0:80:80"
volumes:
  mongodata:
