version: '3.6'
services:
  event_processor:
    image: in2itchicago/event_processor:20200208.1
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    environment:
      - DEBUG=0
      - VERBOSE_OUTPUT=0
      - SCHEDULE_INTERVAL=120
      - RUN_SCHEDULER=1
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200M'
  event_service:
    image: in2itchicago/event_service:20200208.1
    command: "yarn run start:prod"
    labels:
      caddy.address: api.${SERVER_NAME:-localhost}:${SERVER_PORT:-80}
    environment:
      - HOST=/var/run/postgresql
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200M'
  in2it_site:
    image: in2itchicago/in2it_site:20200208.1
    command: "yarn run start"
    environment:
      - "IN2IT_API_URL=${IN2IT_API_URL_PROD:-http://api.localhost}"
    labels:
      caddy.address: ${SERVER_NAME:-localhost}:${SERVER_PORT:-80} www.${SERVER_NAME:-localhost}:${SERVER_PORT:-80}
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200M'
  ndscheduler:
    image: in2itchicago/ndscheduler:20200208.1
    command: "python -u simple_scheduler/scheduler.py"
    environment:
      - DEBUG=0
      - HOSTNAME=/var/run/postgresql
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200M'
  caddy:
    volumes:
      - caddy_certs:/root/.caddy
  postgres:
    deploy:
      restart_policy:
        condition: none
  pgadmin:
    deploy:
      restart_policy:
        condition: none
  portainer:
    deploy:
      restart_policy:
        condition: none
volumes:
  caddy_certs: