version: '3.6'
services:
  mongo:
    image: "mongo:4.1.6"
    volumes:
      - mongodata:/data/db
  event_service:
    image: "event_service"
  event_processor:
    image: "event_processor"
  in2it_site:
    image: "in2it_site"
  nginx:
    image: "nginx:1.15.8"
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "0.0.0.0:80:80"
volumes:
  mongodata:
