version: '3.6'
services:
  event_service:
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./event_service:/usr/src/app/event_service
      - ./.event_service_data/vscode_server:/root/.vscode-server
    labels:
      caddy.address: api.localhost:80
    environment:
      - HOST=postgres
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
  event_processor:
    command: sh -c "chmod +x entrypoint.sh && nodemon --exec ./entrypoint.sh"
    environment:
      - DEBUG=${EVENT_PROCESSOR_DEBUG}
      - VERBOSE_OUTPUT=${VERBOSE_OUTPUT}
      - RUN_SCHEDULER=${RUN_SCHEDULER}
      - SCHEDULE_INTERVAL=5
      - SPIDER_NAME=${SPIDER_NAME}
    volumes:
      - ./event_processor:/usr/src/app/event_processor
      - event_processor_data:/usr/src/app/event_processor/data/
      - event_processor_lock:/usr/src/app/event_processor/lock/
      - event_processor_scrapy:/usr/src/app/event_processor/.scrapy/
      - ./.event_processor_data/vscode_server:/root/.vscode-server
  in2it_site:
    command: sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - ./in2it_site:/usr/src/app/in2it_site
      - ./.in2it_site/vscode_server:/root/.vscode-server
    environment:
      - IN2IT_API_URL=${IN2IT_API_URL:-http://api.localhost}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
    labels:
      caddy.address: localhost:80
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks: 
      - in2it
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ndscheduler:
    command: sh -c "chmod +x entrypoint.sh && nodemon --exec ./entrypoint.sh"
    volumes:
      - ../ndscheduler:/usr/src/app/ndscheduler
      - ndscheduler_modules:/usr/src/app/ndscheduler/node_modules/
      - ../.ndscheduler_data/vscode_remote:/root/vscode-remote
    environment:
      - DEBUG=${SCHEDULER_DEBUG}
      - HOSTNAME=postgres
  pgadmin:
    image: dpage/pgadmin4:4.15
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=7000
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "7000:7000"
    # pgadmin spams logs with http request notifications
    logging:
      driver: none
    networks: 
      - in2it
  portainer:
    image: "portainer/portainer:1.22.2"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks: 
      - in2it
volumes:
  ndscheduler_modules:
  postgres_data:
  event_processor_data:
  event_processor_lock:
  event_processor_scrapy:
  portainer_data:
  pgadmin_data: