version: '3.2'
services:
  mongo:
    image: "mongo:4.1.7"
    volumes:
      - mongodata:/data/db
      - ./mongoconfig:/data/configdb
    ports:
      - "27017:27017"
  event_service:
    image: "event_service_dev"
    ports:
      - target: 5000
        published: 5000
        mode: host
      - "5858:5858"
    deploy:
      mode: global
  event_processor:
    image: "event_processor_dev"
    ports:
      - "6800:6800"
      - "5860:5860"
  in2it_site:
    image: "in2it_site_dev"
    environment:
      - API_URL=${API_URL:-api.localhost}
    ports:
      - "3000:3000"
      - "5859:5859"
  nginx:
    image: "nginx_dev"
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "0.0.0.0:80:80"
    # Sometimes nginx crashes if the site doesn't come up in time
    restart: on-failure
  portainer:
    image: "portainer/portainer:1.20.1"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
  ndscheduler:
    image: ndscheduler
    command: ["./node_modules/nodemon/bin/nodemon.js", "-L", "-u", "simple_scheduler/scheduler.py"]
    ports: 
      - "8888:8888"
      - "5861:5861"
    volumes:
      - ../ndscheduler:/usr/src/app/ndscheduler
      - ndscheduler_modules:/usr/src/app/ndscheduler/node_modules/
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=simple_scheduler.settings
      - DEBUG=0
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:4.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=7000
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "7000:7000"
volumes:
  mongodata:
  portainerdata:
  ndscheduler_modules:
  postgres_data:
  pgadmin_data: